version: '3'

services: 
  php:
    image: ningzhou1980/yii2-docker-production:1.0
    depends_on: 
      - redis
    volumes: 
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/config/prod/php.ini:/usr/local/etc/php/php.ini
    environment: 
      PHP_IDE_CONFIG: "serverName=agency.lawonline.ning.nz"
      ENABLE_PHPFPM: "true"
      ENABLE_CRON_JOB: "false"
      ENABLE_YII2_QUEUE: "true"
    networks: 
      default:
        aliases: 
          - agencies.php
      app-bridge:
        aliases: 
          - agencies.php
      db-bridge:
  nginx:
    image: nginx:latest
    depends_on: 
      - php
    networks: 
      default:
        aliases: 
          - agency.nginx
      app-bridge:
        aliases: 
          - agency.lawonline.ning.nz
    labels: 
      - "traefik.frontend.rule=Host:agency.lawonline.ning.nz"
      - "traefik.enable=true"
    volumes: 
      - ./:/app:delegated
      - ./docker/config/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "no"]
    hostname: redis
    volumes:
      - redis-data:/data
volumes: 
  redis-data:
networks:
  app-bridge:
    external: true
  db-bridge:
    external: true